config/routes.rb
Ebuzz::Application.routes.draw do
  root to: 'static_pages#home'

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
#change var proxy value to "" if you are not behind a proxy server else use the proxy 
#and if your proxy server doesn't require a user name and password just use :proxy in place of :proxy_http_basic_authentication 
#and the "proxy:port" in the value instead of ["proxy:port", "username", "password"]

class StaticPagesController < ApplicationController

  def home
    require 'nokogiri'
    require 'open-uri'
    require 'json'
    proxy = ""
	if params[:search]
		if params[:type] == '2'
		    query = params[:search].to_s
			url = "http://www.tastekid.com/like/#{CGI::escape(query)}/movies"
			if (proxy == "")
				doc = Nokogiri::HTML(open(url))
			else
				doc = Nokogiri::HTML(open(url,:proxy_http_basic_authentication => ["proxy:port", "username", "password"]))
			end
			 @heading = doc.css(".movies h2").text  
			  doc.css(".resourcelist span").each do
				 @simsearch = doc.css(".resourcelist span").map(&:text).join(" | ")
			  end
			@similarities = @simsearch.split(" | ")
			i = 0
			@simsearch_datatype = Array.new()
			@similarities.each do |each|
		     	@simsearch_datatype[i] = 'm'				
				i = i+1
			  end
            if (doc.at_css('.noresults'))
        		@e = 1
				@heading_before = doc.css(".emmysays .no-list").text
                flash.now[:error] = @heading_before
			else
				@e = 0
				@heading_before = doc.css(".no-list").text
                flash.now[:success] = @heading_before
			end
		end
		if params[:type] == '3'
			query = params[:search].to_s
			url = "http://www.tastekid.com/like/#{CGI::escape(query)}/music"
			if (proxy == "")
				doc = Nokogiri::HTML(open(url))
			else
				doc = Nokogiri::HTML(open(url,:proxy_http_basic_authentication => ["proxy:port", "username", "password"]))
			end
			 @heading = doc.css(".music h2").text  
			  doc.css(".resourcelist span").each do
				 @simsearch = doc.css(".resourcelist span").map(&:text).join(" | ")
			  end
			@similarities = @simsearch.split(" | ")
			i = 0
			@simsearch_datatype = Array.new()
			@similarities.each do |each|
		     	@simsearch_datatype[i] = 's'				
				i = i+1
			  end
            if (doc.at_css('.noresults'))
        		@e = 1
				@heading_before = doc.css(".emmysays .no-list").text
                flash.now[:error] = @heading_before
			else
				@e = 0
				@heading_before = doc.css(".no-list").text
                flash.now[:success] = @heading_before
			end
		end
		if params[:type] == '4'
			query = params[:search].to_s
			url = "http://www.tastekid.com/like/#{CGI::escape(query)}/books"
			if (proxy == "")
				doc = Nokogiri::HTML(open(url))
			else
				doc = Nokogiri::HTML(open(url,:proxy_http_basic_authentication => ["proxy:port", "username", "password"]))
			end
			 @heading = doc.css(".books h2").text  
			  doc.css(".resourcelist span").each do
				 @simsearch = doc.css(".resourcelist span").map(&:text).join(" | ")
			  end
			@similarities = @simsearch.split(" | ")
			i = 0
			@simsearch_datatype = Array.new()
			@similarities.each do |each|
		     	@simsearch_datatype[i] = 'b'				
				i = i+1
			  end
            if (doc.at_css('.noresults'))
        		@e = 1
				@heading_before = doc.css(".emmysays .no-list").text
                flash.now[:error] = @heading_before
			else
				@e = 0
				@heading_before = doc.css(".no-list").text
                flash.now[:success] = @heading_before
			end
		end
		if params[:type] == '5'
			query = params[:search].to_s
			url = "http://www.tastekid.com/like/#{CGI::escape(query)}/authors"
			if (proxy == "")
				doc = Nokogiri::HTML(open(url))
			else
				doc = Nokogiri::HTML(open(url,:proxy_http_basic_authentication => ["proxy:port", "username", "password"]))
			end
			 @heading = doc.css(".authors h2").text  
			  doc.css(".resourcelist span").each do
				 @simsearch = doc.css(".resourcelist span").map(&:text).join(" | ")
			  end
			@similarities = @simsearch.split(" | ")
			i = 0
			@simsearch_datatype = Array.new()
			@similarities.each do |each|
		     	@simsearch_datatype[i] = 'a'				
				i = i+1
			  end
            if (doc.at_css('.noresults'))
        		@e = 1
				@heading_before = doc.css(".emmysays .no-list").text
                flash.now[:error] = @heading_before
			else
				@e = 0
				@heading_before = doc.css(".no-list").text
                flash.now[:success] = @heading_before
			end
		end
		if params[:type] == '6'
			query = params[:search].to_s
			url = "http://www.tastekid.com/like/#{CGI::escape(query)}/shows"
			if (proxy == "")
				doc = Nokogiri::HTML(open(url))
			else
				doc = Nokogiri::HTML(open(url,:proxy_http_basic_authentication => ["proxy:port", "username", "password"]))
			end
			 @heading = doc.css(".shows h2").text  
			  doc.css(".resourcelist span").each do
				 @simsearch = doc.css(".resourcelist span").map(&:text).join(" | ")
			  end
			@similarities = @simsearch.split(" | ")
			i = 0
			@simsearch_datatype = Array.new()
			@similarities.each do |each|
		     	@simsearch_datatype[i] = 'h'				
				i = i+1
			  end
            if (doc.at_css('.noresults'))
        		@e = 1
				@heading_before = doc.css(".emmysays .no-list").text
                flash.now[:error] = @heading_before
			else
				@e = 0
				@heading_before = doc.css(".no-list").text
                flash.now[:success] = @heading_before
			end
		end
		if params[:type] == '7'
			query = params[:search].to_s
			url = "http://www.tastekid.com/like/#{CGI::escape(query)}/games"
			if (proxy == "")
				doc = Nokogiri::HTML(open(url))
			else
				doc = Nokogiri::HTML(open(url,:proxy_http_basic_authentication => ["proxy:port", "username", "password"]))
			end
			 @heading = doc.css(".games h2").text  
			  doc.css(".resourcelist span").each do
				 @simsearch = doc.css(".resourcelist span").map(&:text).join(" | ")
			  end
			@similarities = @simsearch.split(" | ")
			i = 0
			@simsearch_datatype = Array.new()
			@similarities.each do |each|
		     	@simsearch_datatype[i] = 'g'				
				i = i+1
			  end
            if (doc.at_css('.noresults'))
        		@e = 1
				@heading_before = doc.css(".emmysays .no-list").text
                flash.now[:error] = @heading_before
			else
				@e = 0
				@heading_before = doc.css(".no-list").text
                flash.now[:success] = @heading_before
			end
		end
		if params[:type] == '1'
			redirect_to root_path, :flash => { :error => "Add a genre to the type of search." } 
		end
	elsif params[:info]
		query = params[:info].to_s
		type = params[:type].to_s
		url = "http://www.tastekid.com/ask/ws/info?q=#{CGI::escape(query)}&t=#{CGI::escape(type)}"
		if (proxy == "")
			doc = Nokogiri::HTML(open(url))
		else
			doc = Nokogiri::HTML(open(url,:proxy_http_basic_authentication => ["proxy:port", "username", "password"]))
		end
		@info_json = doc.css("body").text
		@info = JSON.parse(@info_json)
		respond_to do |format|
		    format.json { render :json => @info }
		end
	else
		url = "http://www.tastekid.com/"
		if (proxy == "")
				doc = Nokogiri::HTML(open(url))
			else
				doc = Nokogiri::HTML(open(url,:proxy_http_basic_authentication => ["proxy:port", "username", "password"]))
			end
		@heading = doc.css(".resourcelist h2").text
		@simsearch_datatype = Array.new()
		x = 0
		doc.css(".rsrc").each do |link|
		     @simsearch_datatype[x] = link["data-type"]
		     x = x+1
		  end
		doc.css(".rsrc span").each do
		     @simsearch = doc.css(".rsrc span").map(&:text).join(" | ")
		  end
		@similarities = @simsearch.split(" | ")
		@e = 0
	end
  end

  def about
  end

  def help
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    © e-buZZ. All rights reserved | Created by <a href="http://www.facebook.com/rajeev.reddy.d">drreddy</a>
  </small>
  <nav>
    <ul>
      <li>Powered by Ruby on Rails, Bootstrap and Nokogiri</li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "e-buZZ", '#', id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    root_path %></li>
          <li><%= link_to "About Me",   about_path %></li>
          <li><%= link_to "About e-buZZ",    help_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>E-Buzz | <%= yield(:title) %></title>
    <meta name="Description" CONTENT="This is an online platform powered by ruby on rails and nokogiri that provide recommendations and help you discover new music, movies, shows, books, authors or games, based on what you like.">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <script src="http://krssg.in/js/bootstrap.js"></script>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
  	<%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/_error.html.erb
<div class="error" style="" >
  Sorry, we couldn't think of anything related to your favorite stuff right now.<br>
  <strong>1.</strong> <strong>Check your spelling</strong> - maybe you've slipped a mistake.<br>
  <strong>2.</strong> Be sure you wrote <strong>the correct (full) title of your favorite stuff</strong>.<br>
  <strong>3.</strong> If you've written me more than one favorite band/movie/book/show/author/game, be sure to <strong>separate these titles using commas</strong>.<br>
  If none of these works for you, please <strong>try searching for more popular bands, movies, shows, books, authors or games</strong> in the same genre.
</div>
<h3>here are some trending searches</h3>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Me') %>
<div class="hero-unit">
  <h2>About Me</h2>
  Hey, I am Rajeev Reddy, a Third Year Undergraduate student of Chemical Engineering Department, IIT Kharagpur. First of all right of the bat for a chemical engineering student I can say that I am good at programming. I love web based programming most and have been working with it. I am good at the back end part of the web programming but still far behind designing the front end part. Apart from Website building I have major interest in other programming languages like C, Ruby on Rails, C#, C++ and Algorithms Design and Analysis. I have participated in various coding competitions like Yahoo Hack U 2012 and 2013, Microsoft Appathon 2012 both held at IIT Kharagpur.
</div>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<div class="hero-unit">
  <h2>About e-buZZ</h2>
  This is an online platform powered by ruby on rails and nokogiri that provide recommendations and help you discover new music, movies, shows, books, authors or games, based on what you like. Some call me a recommendation system or a discovery engine, but I prefer to simply be called e-buZZ. 
</div>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<div class="hero-unit">

  <h2>
    Welcome to the e-buZZ favourites search
  </h2>
    <%= form_tag root_path, :method => 'post' do%>
		<div style="float:left; width:75%;"><%= text_field_tag :search, params[:search], placeholder: "Search for your favourite movies, shows, authors, books, music, games and get similar results..." %></div>
		<div style="float:left; padding-left:20px; "><%= select_tag :type, options_for_select([['Genre', 1], ['Movies', 2], ['Music', 3], ['Books', 4], ['Authors', 5], ['Shows', 6], ['Games', 7]]) %></div>
		<div style="float:left; padding-left:10px; "><%= submit_tag "Search", class: "btn btn-default btn-info", :name => 'nil' %></div>
	<% end %>
  <div style="padding-top:50px; min-height:270px;">
  <%= render 'error' if @e == 1 %>
    <h3><%= @heading %></h3>
  <% i=0 %>
	<% @similarities.each do |sim| %> 
      <div style="float:left; padding:10px; background-color:#eeeeee;"><a href="#<%= i %>" id ="flip<%= i %>" class="test" data-toggle="modal" rel="<%= @simsearch_datatype[i] %>"><b><%= sim %></b></a></div>
      <div id="<%= i %>" class="modal hide fade" style="width:760px !important; margin-left:-380px !important;" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
        <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 id="myModalLabel"><%= sim %></h4>
      </div>
      <div class="modal-body" style="text-align:justify !important">
        <div class="content"><center><img src="http://gigbytes.net23.net/assets/loading.gif"/></center></div>
      </div>
      <div class="modal-footer">
        Click on the outside or use the cross mark in the header
      </div>
      </div>
    <% i = i+1 %>
    <% end %>
  </div>
  <div id="num" style="display:none;"><%= i-1 %></div>
</div>